# Site settings
title: Nemboru's Workshop
email: felipetavres@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I consider myself as a code artisan. And i'm proud of what i do.
  I'am also pragmatic, simplistic and cheerful.
baseurl: ""
url: "http://nemoNoboru.github.io/"
#twitter_username: no twitter
github_username:  nemoNoboru

# Build settings
markdown: kramdown

paginate: 4

author: Nemo Noboru

gems: [jekyll-paginate]
